export const DEFAULT_PLANS = [
    {
        planId: '1_MONTH',
        name: 'Monthly Plan',
        description: 'Perfect for traders who want to try our platform month by month',
        razorpayPlanId: process.env.RAZORPAY_PLAN_1_MONTH || 'plan_monthly_placeholder',
        amount: 599,
        currency: 'INR',
        billingCycle: 'monthly',
        billingPeriod: 1,
        bonusMonths: 0,
        totalMonths: 1,
        monthlyEquivalent: 599,
        savingsPercentage: 0,
        isRecurring: false, // One-time order instead of subscription
        features: [
            { name: 'Full trading journal access', description: 'Track unlimited trades', included: true },
            { name: 'Advanced analytics & insights', description: 'Detailed performance metrics', included: true },
            { name: 'AI-powered trade assistant', description: 'Get intelligent trade suggestions', included: true },
            { name: 'Performance tracking', description: 'Monitor your progress over time', included: true },
            { name: 'Psychology analysis', description: 'Understand your trading mindset', included: true },
        ],
        isPopular: false,
        displayOrder: 1,
        isActive: true,
        trialDays: 7
    },
    {
        planId: '3_MONTHS',
        name: '3 Months Plan',
        description: 'Great for traders getting serious',
        razorpayPlanId: process.env.RAZORPAY_PLAN_3_MONTHS || 'plan_3months_placeholder',
        amount: 1699,
        currency: 'INR',
        billingCycle: 'quarterly',
        billingPeriod: 3,
        bonusMonths: 0,
        totalMonths: 3,
        monthlyEquivalent: 566,
        savingsPercentage: 5,
        isRecurring: true,
        features: [
            { name: 'Full trading journal access', description: 'Track unlimited trades', included: true },
            { name: 'Advanced analytics & insights', description: 'Detailed performance metrics', included: true },
            { name: 'AI-powered trade assistant', description: 'Get intelligent trade suggestions', included: true },
            { name: 'Performance tracking', description: 'Monitor your progress over time', included: true },
            { name: 'Psychology analysis', description: 'Understand your trading mindset', included: true },
        ],
        isPopular: false,
        displayOrder: 2,
        isActive: true,
        trialDays: 7
    },
    {
        planId: '6_MONTHS',
        name: '6 Months Plan',
        description: 'Best for committed traders',
        razorpayPlanId: process.env.RAZORPAY_PLAN_6_MONTHS || 'plan_6months_dev',
        amount: 2999,
        currency: 'INR',
        billingCycle: 'half_yearly',
        billingPeriod: 6,
        bonusMonths: 0,
        totalMonths: 6,
        monthlyEquivalent: 499,
        savingsPercentage: 17,
        isRecurring: true,
        features: [
            { name: 'Full trading journal access', description: 'Track all your trades in one place', included: true },
            { name: 'Advanced analytics & insights', description: 'Understand your trading patterns', included: true },
            { name: 'AI-powered trade assistant', description: 'Get intelligent trading suggestions', included: true },
            { name: 'Performance tracking', description: 'Monitor your progress over time', included: true },
            { name: 'Psychology analysis', description: 'Understand your trading psychology', included: true },
        ],
        isPopular: true,
        displayOrder: 3,
        isActive: true,
        trialDays: 7
    },
    {
        planId: '12_MONTHS',
        name: 'Yearly Plan',
        description: 'Maximum value for serious traders',
        razorpayPlanId: process.env.RAZORPAY_PLAN_12_MONTHS || 'plan_12months_dev',
        amount: 5990,
        currency: 'INR',
        billingCycle: 'yearly',
        billingPeriod: 12,
        bonusMonths: 0,
        totalMonths: 12,
        monthlyEquivalent: 499,
        savingsPercentage: 17,
        isRecurring: true,
        features: [
            { name: 'Full trading journal access', description: 'Track all your trades in one place', included: true },
            { name: 'Advanced analytics & insights', description: 'Understand your trading patterns', included: true },
            { name: 'AI-powered trade assistant', description: 'Get intelligent trading suggestions', included: true },
            { name: 'Performance tracking', description: 'Monitor your progress over time', included: true },
            { name: 'Psychology analysis', description: 'Understand your trading psychology', included: true },
            { name: 'Priority support', description: 'Get help when you need it', included: true },
        ],
        isPopular: false,
        displayOrder: 4,
        isActive: true,
        trialDays: 7
    }
];
