import mongoose from "mongoose";

const TradeSchema = new mongoose.Schema({
  userId: { type: String, required: true },
  id: { type: String, required: true, unique: true },
  session: { type: mongoose.Schema.Types.ObjectId, ref: 'Session', required: true },
  date: String,
  time: String,
  pair: String,
  buySell: String,
  setupType: String,
  entryType: String,
  timeFrameUsed: String,
  trailWorked: String,
  imageOfPlay: String,
  linkToPlay: String,
  uploadedImage: String,
  uploadedImageName: String,
  entryPrice: Number,
  exitPrice: Number,
  pipsLostCaught: Number,
  pnl: Number,
  riskPerTrade: Number,
  rFactor: Number,
  typeOfTrade: String,
  entryModel: String,
  confluences: String,
  rulesFollowed: String,
  tfUsed: String,
  fearToGreed: Number,
  fomoRating: Number,
  executionRating: Number,
  imagePosting: String,
  notes: String,
}, { timestamps: true });

export default mongoose.models.Trade || mongoose.model("Trade", TradeSchema);